apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: scipian
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: scipian-config
  namespace: scipian
data:
  state-bucket: cnqr-scipian-backend
  state-locking: cnqr-scipian-backend-locking
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: scipian
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: scipian
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /root/manager
        image: controller:latest
        name: manager
        env:
          - name: SCIPIAN_STATE_BUCKET
            valueFrom:
              configMapKeyRef:
                name: scipian-config
                key: state-bucket
          - name: SCIPIAN_STATE_LOCKING
            valueFrom:
              configMapKeyRef:
                name: scipian-config
                key: state-locking
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
