apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: scipian
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: scipian-config
  namespace: scipian
data:
  state-bucket: cnqr-scipian-backend
  state-locking: cnqr-scipian-backend-locking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: scipian
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: quay.io/scipian/terraform-controller:v0.0.7
        name: manager
        env:
          - name: SCIPIAN_STATE_BUCKET
            valueFrom:
              configMapKeyRef:
                name: scipian-config
                key: state-bucket
          - name: SCIPIAN_STATE_LOCKING
            valueFrom:
              configMapKeyRef:
                name: scipian-config
                key: state-locking
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
