apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: workspaces.terraform.scipian.io
spec:
  group: terraform.scipian.io
  names:
    kind: Workspace
    plural: workspaces
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            backend:
              properties:
                bucket:
                  type: string
                key:
                  type: string
                region:
                  type: string
                type:
                  type: string
              required:
              - type
              - bucket
              - key
              - region
              type: object
            envVars:
              type: object
            image:
              type: string
            secret:
              type: string
            tfVars:
              type: object
            workingDir:
              type: string
          required:
          - image
          - secret
          - workingDir
          - backend
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
