
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    creationTimestamp: null
    name: manager-role-k8s-types
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/volumes
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
    